### Signup
# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Bruno Britto",
    "email": "bruno@email.com",
    "password": "123456"
}

### Login
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "bruno@email.com",
    "password": "123456"
}

### Info
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Get Feed
GET http://localhost:3003/user/feed
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Info By Id
@userId = f03017bb-2c08-4cdc-bb63-7fbd7cebe01f
GET http://localhost:3003/user/{{userId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### RECIPES

### Create Recipe

POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "title": "Hamburguer",
    "description": "Hamburguer Podrão",
    "step_by_step":
      "Pegue o pão, faça aqueles hamburgueres de supermercado e jogue tudo que tiver dentro da geladeira nele."
}

### Get Recipe
@recipeId = b3eae06c-0741-4b85-83ab-75189cf5f3cb
GET http://localhost:3003/recipe/{{recipeId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}


### FOLLOW

### Follow User
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "idToFollow": "2d406fc5-d020-4b60-a002-68e5d8aa911f"
}
### Unfollow User
POST http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "idToUnfollow": "7079b8e4-95cd-48aa-82a9-77454e94b789"
}