### Signup
# @name signup
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Bruno Britto",
    "email": "bruno@email.com",
    "password": "123456"
}

### Login
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### Info
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Get Feed
GET http://localhost:3003/user/feed
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Info By Id
@userInfoId = bb9b7ee8-ae4b-4bd1-9bd6-e7e21594399b
GET http://localhost:3003/user/{{userInfoId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Delete User
@userToDeleteId = bb9b7ee8-ae4b-4bd1-9bd6-e7e21594399b
DELETE http://localhost:3003/user/{{userToDeleteId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### RECIPES

### Create Recipe

POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "title": "Pizza",
    "description": "Pizza de Frango",
    "step_by_step":
      "Pegue a pizza, coloque molho de tomate, queijo e o frango."
}

### Get Recipe
@recipeInfoId = e03134e8-0b51-4561-bcca-13356850c763
GET http://localhost:3003/recipe/{{recipeInfoId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Delete Recipe
@recipeToDeleteId = 6d7f00ea-a454-4a01-bad9-6f57f25344bc
DELETE http://localhost:3003/recipe/{{recipeToDeleteId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Edit Recipe
@recipeToEditId = 3bc68f84-4df8-4432-939f-2edf4a82c630
PUT http://localhost:3003/recipe/{{recipeToEditId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "title": "Pizza com bastante queijo",
    "description": "Pizza de quatro queijos",
    "step_by_step":
      "Pegue a massa, passe o molho de tomate, jogue os diferentes tipos de queijo e, caso queira, finalize com orégano..."
}

### FOLLOW

### Follow User
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "idToFollow": "bb9b7ee8-ae4b-4bd1-9bd6-e7e21594399b"
}

### Unfollow User
POST http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "idToUnfollow": "bb9b7ee8-ae4b-4bd1-9bd6-e7e21594399b"
}