### Signup
# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Bruno Britto",
    "email": "bruno@email.com",
    "password": "123456"
}

### Login
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "bruno@email.com",
    "password": "123456"
}


### Info
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Info By Id
@id = f03017bb-2c08-4cdc-bb63-7fbd7cebe01f
GET http://localhost:3003/user/{{id}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}


### RECIPES

### Create Recipe

POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "title": "Pizza",
    "description": "Pizza de frango",
    "step_by_step":
      "Pegue a massa, passe o molho de tomate, jogue o queijo e o frango por cima. Caso queira, finalize com orégano."
}