### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Beltrano",
    "email": "beltrano2@gmail.com",
    "password": "abc123"
}

### 2) Login
# @name login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Get users
GET http://localhost:3003/users
Authorization: {{login.response.body.token}}

### 3) Delete user
@id = b67c6ee5-c06b-470f-8470-71803e17e509
DELETE http://localhost:3003/users/{{id}}
Authorization: {{login.response.body.token}}

### 4) Edit user
@id = bb9b7ee8-ae4b-4bd1-9bd6-e7e21594399b
PUT http://localhost:3003/users/{{id}}
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
    "name": "Astrodev3"
}