## Buyer
### Create Buyer
# @name createBuyer
POST http://localhost:3003/buyer/create
Content-Type: application/json

{
    "name": "Germana Marinho",
    "email": "germana@email.com",
    "password": "123456",
    "cpf": "10987654321"
}

### Login
# @name login
POST http://localhost:3003/buyer/login
Content-Type: application/json

{
    "email": "bruno@email.com",
    "password": "123456"
}

### Get Buyer
GET http://localhost:3003/buyer
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Get Buyer by Id
@buyerId = 0f2a2821-8a7c-4793-8d1a-790767b5219d
GET http://localhost:3003/buyer/{{buyerId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Delete Buyer
@buyerId = 0f2a2821-8a7c-4793-8d1a-790767b5219d
DELETE http://localhost:3003/buyer/{{buyerId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

## Card
### Create Card
# @name createCard
POST http://localhost:3003/card/create
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "cardNumber": "372795086309759",
    "cardHolderName": "Bruno Britto",
    "cardExpirationDate": "05/33",
    "cardCVV": 333
}

### Delete Card
# @name deleteCard
@cardNumberToDelete = 2720499880582126
DELETE http://localhost:3003/card/{{cardNumberToDelete}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Get All Cards
# @name getAllCards
GET  http://localhost:3003/card/all
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Card By Card Number
# @name getSingleCard
@cardNumber = 5555666677778884
GET http://localhost:3003/card/{{cardNumber}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

## Payment
### Create Payment
# @name createPayment
POST http://localhost:3003/payment/create
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

{
    "amount": 500,
    "type": "CREDIT_CARD",
    "cardNumber": "5555666677778884"
}

### Delete Payment
# @name deletePayment
@paymentIdToDelete = ebcb9863-4bd7-4911-8225-22b316ceacd8
DELETE http://localhost:3003/payment/{{paymentIdToDelete}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### getAllPayments
# @name getAllPayments
GET http://localhost:3003/payment/status
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

### Payment Status
# @name singlePayment
@paymentId = ebcb9863-4bd7-4911-8225-22b316ceacd8
GET http://localhost:3003/payment/status/{{paymentId}}
Content-Type: application/json
Authorization: {{login.response.body.accessToken}}

